#!/usr/bin/env bash
# Transfers a file from our client to a server
#
# variables
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi

# assigninh paraments to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# checking if the transfer was successful
if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERRED SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
fi
